
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: krolnoeurnrpisb/npitlaravel:1.0.0
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    # env_file:
    #   - .env.docker
    ports:
      - "8000:80"
    environment:
      APP_NAME: "Laravel"
      APP_ENV: "local"
      APP_KEY: "base64:MA8+6xX/wW50gVv6zvOCocbD2Eacb9cKmCX8fy7tui0="
      APP_DEBUG: "true"
      APP_TIMEZONE: "UTC"
      APP_URL: "http://localhost"
      APP_LOCALE: "en"
      APP_FALLBACK_LOCALE: "en"
      APP_FAKER_LOCALE: "en_US"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

#   nginx:
#     image: nginx:alpine
#     container_name: laravel_nginx
#     restart: unless-stopped
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - laravel

networks:
  laravel:

volumes:
  db_data:
